### PR TITLE
Add extension method to remove counter

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
@enkelmedia  I'm sure if this is an desired addition. But I really like to remove a counter from the `startup.cs` class.

### CODE REVIEW

**Comment by enkelmedia** [comment]
Thanks @erikjanwestendorp! I think this looks useful, just need to check it a little closer and update the docs. 

Just wondering, is there anything that prevents you from doing this in your startup?

```
builder.TheDashboardCounters().Remove<T>();
```

Given that the above works, the only difference would be some syntactic sugar?

```
builder.RemoveCounterDashboard<T>();
```

Or I'm I missing something?

**Comment by erikjanwestendorp** [comment]
@enkelmedia Thanks for your quick reply. 

```csharp
builder.TheDashboardCounters().Remove<T>();
```
Returns the `DashboardCountersCollectionBuilder` and not the 'IUmbracoBuilder' and therefore it cannot be used in the  `startup.cs` class.

**Comment by enkelmedia** [comment]
Ahh! You mean that you want to be able to chain them in startup? That makes sense!

**Comment by erikjanwestendorp** [comment]
Yes, indeed! That would be great 😄

**Comment by enkelmedia** [comment]
Sorry for the late merge, I'll make sure to include this in the next release!

**Pull request merged**
